// Starts the hub on a spare port with a temp data dir, sends inputs, checks replies and WebSocket state.
import { spawn } from "node:child_process";
import { mkdtempSync, rmSync, cpSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import WebSocket from "ws";
const hub = join(dirname(fileURLToPath(import.meta.url)), "..");
const PORT = 18047;
const p = spawn("node", ["src/server.mjs"], { cwd: hub, env: { ...process.env, PORT, ANTHROPIC_API_KEY: "", GEMINI_API_KEY: "", HUB_TOKEN: "" }, stdio: ["ignore", "pipe", "pipe"] });
p.stderr.on("data", d => process.stderr.write(d));
await new Promise(r => p.stdout.once("data", r));
const post = async (body) => (await fetch(`http://127.0.0.1:${PORT}/input`, { method: "POST", body: JSON.stringify(body) })).json();
const results = [];
const check = (name, ok, extra = "") => { results.push(ok); console.log((ok ? "PASS " : "FAIL ") + name + (extra ? " → " + extra : "")); };
let r;
r = await post({ kind: "notification", from: "Zepto", text: "Your Zepto order of ₹342 is out for delivery" }); check("order from notification", /Zepto/.test(r.line), r.line);
r = await post({ kind: "text", text: "what did I order today?" }); check("ask today's orders", /Zepto/.test(r.line), r.line);
r = await post({ kind: "text", text: "remember I like filter coffee, no sugar" }); check("log a note", r.line === "Saved.", r.line);
r = await post({ kind: "voice", text: "did laundry" }); check("chore done", /Laundry: done/i.test(r.line), r.line);
r = await post({ kind: "text", text: "how's the scooter?" }); check("scooter without token", /can't see the scooter/i.test(r.line), r.line);
r = await post({ kind: "text", text: "so tired today yaar" }); check("feeling check-in", /I'm here/.test(r.line), r.line);
r = await post({ kind: "nfc", data: { tag: "helmet" } }); check("helmet NFC tap", /Ride safe/.test(r.line), r.line);
r = await post({ kind: "telemetry", text: "ride ended", data: { lat: 12.97, lon: 77.64 }, from: "ather-bt" }); check("ride end saves parking", /Parked/.test(r.line), r.line);
r = await post({ kind: "sms", text: "Rs.240.00 debited from a/c XX12 to ZEPTO", from: "bank" }); check("bank sms spend", /Logged ₹240/.test(r.line), r.line);
r = await post({ kind: "telemetry", text: "arrived at office" }); check("office arrival", /At office/.test(r.line), r.line);
const ws = new WebSocket(`ws://127.0.0.1:${PORT}/ws?body=keychain&compact=1`);
const mood = await new Promise(res => ws.on("message", m => { const j = JSON.parse(m); if (j.t === "mood") res(j); }));
check("keychain gets compact mood", typeof mood.eyeOpen === "number" && mood.label, JSON.stringify(mood));
ws.send(JSON.stringify({ t: "sense", name: "dizzy" }));
await new Promise(r => setTimeout(r, 300));
const st = await (await fetch(`http://127.0.0.1:${PORT}/api/state`)).json();
check("dizzy only on the keychain", st.bodies.keychain.label === "dizzy" && st.bodies.tablet.label !== "dizzy", st.bodies.keychain.label + " / " + st.bodies.tablet.label);
const face = await fetch(`http://127.0.0.1:${PORT}/`); check("face served", face.ok && (await face.text()).includes("Jeevo's face"));
ws.close(); p.kill();
console.log(results.every(Boolean) ? "ALL PASS" : "SOME FAILED");
process.exit(results.every(Boolean) ? 0 : 1);
